### PR TITLE
Improve readme and gitignore

### PR DESCRIPTION
**Pull request by TransientTetra**

### CODE REVIEW

**Comment by Redcrafter** [comment]
Thanks for contributing.
libglibd-2.0-dev is for the D programming language did you mean libglib2.0-dev?
And if you did it is a dependency of libgtk2.0-dev so you shouldn't have to install it manually.
Was this an issue for you?

**Comment by TransientTetra** [comment]
Hi, yes that was an issue for me, I agree that gtk dependencies should be installed along with it, perhaps debian libraries are not entirely correctly linked. I will remove the library.

**Comment by TransientTetra** [comment]
Or should I change it to libglib (the proper one) and leave as a workaround? It wouldn't change installation process if ligtk hooked properly, and if it doesn't it would install all dependencies

**Comment by Redcrafter** [comment]
It's not a direct dependency so it's probably best to remove it.

**Comment by TransientTetra** [comment]
Done

**Pull request merged**
